directory = File.dirname(__FILE__)

load "#{directory}/../../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"

  config.vm.provision "shell", privileged: false, path: "#{directory}/initialize.sh"
  config.vm.provision "shell", privileged: false, path: "#{directory}/apply.sh"
end
