version: '3'

services:
  config:
    build:
      context: ./
      dockerfile: ./config/Dockerfile
      args:
        TERRAFORM_IMAGE_NAME:
        TERRAFORM_VERSION:
    volumes:
      - config-state:/tmp/vault/config/.terraform/backends/
      - server-config:/tmp/vault/config/artifacts/server/
      - cli-config:/tmp/vault/config/artifacts/cli/

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    cap_add:
      - IPC_LOCK
    volumes:
      - server-config:/vault/config/
      - server-state:/vault/file/
      - server-logs:/vault/logs/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped

  cli:
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    volumes:
      - cli-config:/tmp/vault/cli/config/
      - ./cli/artifacts/:/tmp/vault/cli/state/
    network_mode: host
    environment:
      VAULT_ADDR: ${VAULT_ADDR}

volumes:
  config-state:
  server-config:
  server-state:
  server-logs:
  cli-config:
