version: '3'

services:
  config:
    build:
      context: ./config/
      dockerfile: ./Dockerfile
      args:
        TERRAFORM_IMAGE_NAME:
        TERRAFORM_VERSION:
    volumes:
      - config-state:/tmp/vault/.terraform/backends/
      - config-artifacts-ca:/tmp/vault/artifacts/ca/
      - config-artifacts-server:/tmp/vault/artifacts/server/
      - config-artifacts-init:/tmp/vault/artifacts/init/

  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    cap_add:
      - IPC_LOCK
    volumes:
      - server-state:/vault/file/
      - config-artifacts-server:/vault/config/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  init:
    build:
      context: ./init/
      dockerfile: ./Dockerfile
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    volumes:
      - config-artifacts-init:/tmp/vault/artifacts/init/
    network_mode: host
    environment:
      VAULT_ADDR: ${VAULT_ADDR}

  export:
    build:
      context: ./export/
      dockerfile: ./Dockerfile
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    volumes:
      - ./artifacts/:/tmp/vault/artifacts/export/
      - config-artifacts-ca:/tmp/vault/artifacts/ca/
      - config-artifacts-server:/tmp/vault/artifacts/server/
      - config-artifacts-init:/tmp/vault/artifacts/init/
    network_mode: host
    environment:
      VAULT_ADDR: ${VAULT_ADDR}

volumes:
  config-state:
  config-artifacts-ca:
  config-artifacts-server:
  config-artifacts-init:
  server-state:
