Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.provision "shell", inline: "bash /vagrant/restore.sh", privileged: false
  config.vm.provision "shell", inline: "bash /vagrant/build.sh", privileged: false
end
