version: '3'

services:
  cli:
    build:
      context: ./
      dockerfile: ./cli/Dockerfile
      args:
        CERTBOT_IMAGE_NAME:
        CERTBOT_VERSION:
    volumes:
      - cli-state:/etc/letsencrypt/
      - cli-work:/var/lib/letsencrypt/

volumes:
  cli-state:
  cli-work:
