version: '3'

services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT:
    ports:
      - 5000:5000

  app:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5001
      ASPNETCORE_ENVIRONMENT:
    ports:
      - 5001:5001

  api-proxy:
    build:
      context: ./api/
      dockerfile: ./proxy.Dockerfile
    environment:
      CONSUL_HTTP_ADDR:
      CONSUL_HTTP_TOKEN:
    network_mode: host

  app-proxy:
    build:
      context: ./app/
      dockerfile: ./proxy.Dockerfile
    environment:
      CONSUL_HTTP_ADDR:
      CONSUL_HTTP_TOKEN:
    network_mode: host

  config:
    build:
      context: ./
      dockerfile: ./config.Dockerfile
    environment:
      CONSUL_HTTP_ADDR:
      CONSUL_HTTP_TOKEN:
    network_mode: host
    working_dir: /opt/consul-template/
    volumes:
      - ./:/opt/consul-template/
    command: -config ./config.hcl
