version: '3'

services:
  core-agent:
    build:
      context: ./core/agent/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    volumes:
      - core-agent-config:/consul/config/
      - core-agent-data:/consul/data/
    ports:
      - 8500:8500
    environment:
      VAULT_ADDR:
      VAULT_TOKEN:

  core-config:
    build:
      context: ./core/config/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
        CONSUL_TEMPLATE_IMAGE_NAME:
        CONSUL_TEMPLATE_VERSION:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    volumes:
      - core-agent-config:/tmp/consul/config/
    environment:
      VAULT_ADDR:
      VAULT_TOKEN:

  core-vault:
    build:
      context: ./core/vault/
      args:
        VAULT_IMAGE_NAME:
        VAULT_VERSION:
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID:
      VAULT_ADDR:
      VAULT_TOKEN:

  server-agent:
    build:
      context: ./server/agent/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
    volumes:
      - server-agent-config:/consul/config/
    ports:
      - 8500
    deploy:
      replicas: 1

  server-config:
    build:
      context: ./server/config/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
        CONSUL_TEMPLATE_IMAGE_NAME:
        CONSUL_TEMPLATE_VERSION:
    volumes:
      - server-agent-config:/tmp/consul/config/
    environment:
      VAULT_ADDR:
      VAULT_TOKEN:

  client-agent:
    build:
      context: ./client/agent/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
    volumes:
      - client-agent-config:/consul/config/
    deploy:
      replicas: 1

  client-config:
    build:
      context: ./client/config/
      args:
        CONSUL_IMAGE_NAME:
        CONSUL_VERSION:
        CONSUL_TEMPLATE_IMAGE_NAME:
        CONSUL_TEMPLATE_VERSION:
    volumes:
      - client-agent-config:/tmp/consul/config/
    environment:
      VAULT_ADDR:
      VAULT_TOKEN:

volumes:
  core-agent-config:
  core-agent-data:
  server-agent-config:
  client-agent-config:
