parameters:
  version: ''

jobs:
  - job: ubuntu_${{ replace(parameters.version, '.', '_') }}
    displayName: Ubuntu ${{ parameters.version }}

    pool:
      vmImage: 'ubuntu-${{ parameters.version }}'

    steps:
      - checkout: none

      - script: |
          uname -a
          lsb_release -a

          lscpu
          lsmem
          sudo lshw
        displayName: Initialize System

      - script: |
          df -h
          lsblk

          sudo rm -Rf /usr/local/lib/android
          sudo rm -Rf /usr/local/lib/node_modules

          df -h
          lsblk
        displayName: Initialize Disk

      - script: |
          apt list --installed
        displayName: Initialize Apps
