parameters:
  version: ''

jobs:
  - job: windows_${{ replace(parameters.version, '.', '_') }}
    displayName: Windows ${{ parameters.version }}

    pool:
      vmImage: 'windows-${{ parameters.version }}'

    steps:
      - checkout: none

      - powershell: |
          cmd /c ver

          systeminfo
          Get-ComputerInfo
        displayName: Initialize System

      - powershell: |
          Get-PSDrive
        displayName: Initialize Disk

      - powershell: |
          choco list -i
        displayName: Initialize Apps

      - powershell: |
          $env:POLICY_NAME="hello-world"
          . { iwr -useb https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/deploy.ps1 } | iex
        displayName: Provision

      - powershell: |
          C:/opscode/chef/bin/chef-client.bat --version
        displayName: Test
