parameters:
  version: ''

jobs:
  - job: windows_${{ replace(parameters.version, '.', '_') }}
    displayName: Windows ${{ parameters.version }}

    pool:
      vmImage: 'windows-${{ parameters.version }}'

    steps:
      - checkout: none

      - script: |
          cmd /c ver

          systeminfo
        displayName: Initialize System

      - script: |
          powershell -c Get-PSDrive
        displayName: Initialize Disk

      - script: |
          choco list -i
        displayName: Initialize Apps

      - powershell: |
          choco install -y vagrant
          if ($LASTEXITCODE -eq 3010) { exit 0 }
        displayName: Provision

      - script: |
          vagrant --version
        displayName: Test
        workingDirectory: C:\HashiCorp\Vagrant\bin
