trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/azure/pipeline-agents
pr: none

jobs:
  - job: ubuntu_2204
    displayName: Ubuntu 22.04

    pool:
      vmImage: 'ubuntu-22.04'

    steps:
      - checkout: none

      - script: |
          uname -a
          lsb_release -a

          lscpu
          lsmem
          sudo lshw
        displayName: Initialize System

      - script: |
          df -h
          lsblk

          sudo rm -Rf /usr/local/lib/android
          sudo rm -Rf /usr/local/lib/node_modules

          df -h
          lsblk
        displayName: Initialize Disk

      - script: |
          apt list --installed
        displayName: Initialize Apps

  - job: ubuntu_2004
    displayName: Ubuntu 20.04

    pool:
      vmImage: 'ubuntu-20.04'

    steps:
      - checkout: none

      - script: |
          uname -a
          lsb_release -a

          lscpu
          lsmem
          sudo lshw
        displayName: Initialize System

      - script: |
          df -h
          lsblk

          sudo rm -Rf /usr/local/lib/android
          sudo rm -Rf /usr/local/lib/node_modules

          df -h
          lsblk
        displayName: Initialize Disk

      - script: |
          apt list --installed
        displayName: Initialize Apps

  - job: windows_2022
    displayName: Windows 2022

    pool:
      vmImage: 'windows-2022'

    steps:
      - checkout: none

      - script: |
          cmd /c ver

          systeminfo
          powershell -c get-computerinfo
        displayName: Initialize System

      - powershell: |
          Get-PSDrive
        displayName: Initialize Disk

      - script: |
          choco list -i
        displayName: Initialize Apps

  - job: windows_2019
    displayName: Windows 2019

    pool:
      vmImage: 'windows-2019'

    steps:
      - checkout: none

      - script: |
          cmd /c ver

          systeminfo
          powershell -c get-computerinfo
        displayName: Initialize System

      - powershell: |
          Get-PSDrive
        displayName: Initialize Disk

      - script: |
          choco list -i
        displayName: Initialize Apps
