trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/azure/pipeline-agents
pr: none

jobs:
  - job: ubuntu
    displayName: Ubuntu

    pool:
      vmImage: 'ubuntu-20.04'

    steps:
      - script: |
          uname -a
          lsb_release -a

          sudo lshw
        displayName: Core

      - script: |
          df -h

          sudo du -sh /*
        displayName: Disk

  - job: windows
    displayName: Windows

    pool:
      vmImage: 'windows-2022'

    steps:
      - script: |
          cmd /c ver

          systeminfo
        displayName: Core

      - powershell: |
          Get-PSDrive

          $fso = new-object -com Scripting.FileSystemObject
          gci c:\ -Directory `
            | select @{l='Size'; e={$fso.GetFolder($_.FullName).Size}},FullName `
            | ft @{l='Size [MB]'; e={'{0:N2}    ' -f ($_.Size / 1MB)}},FullName
        displayName: Disk
