parameters:
  version: ''

jobs:
  - job: ubuntu_${{ replace(parameters.version, '.', '_') }}
    displayName: Ubuntu ${{ parameters.version }}

    pool:
      vmImage: 'ubuntu-${{ parameters.version }}'

    steps:
      - checkout: none

      - script: |
          uname -a
          lsb_release -a

          lscpu
          lsmem
          sudo lshw -short
        displayName: Initialize System

      - script: |
          df -h
          # sudo rm -Rf /usr/local/lib/android
          # sudo rm -Rf /usr/local/lib/node_modules
        displayName: Initialize Disk

      - script: |
          apt list --installed
        displayName: Initialize Apps

      - script: |
          curl -Ls https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.sh | bash -s
        displayName: Provision Hello World
        env:
          CHEF_POLICY: hello-world

      - script: |
          chef-client --version
        displayName: Test
