parameters:
  version: ''

jobs:
  - job: windows_${{ replace(parameters.version, '.', '_') }}
    displayName: Windows ${{ parameters.version }}

    pool:
      vmImage: 'windows-${{ parameters.version }}'

    steps:
      - checkout: none

      - script: |
          cmd /c ver

          systeminfo
        displayName: Initialize System

      - script: |
          powershell -c Get-PSDrive
        displayName: Initialize Disk

      - script: |
          choco list -i
        displayName: Initialize Apps

      - powershell: |
          $env:POLICY_NAME="chef-workstation"
          . { iwr -useb https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/deploy.ps1 } | iex
        displayName: Provision

      - script: |
          chef-client.bat --version
          chef-cli.bat --version
        displayName: Test
        workingDirectory: C:\opscode\chef-workstation\bin
