trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/azure/pipeline-agents
pr: none

jobs:
  - job: ubuntu
    displayName: Ubuntu

    pool:
      vmImage: 'ubuntu-22.04'

    steps:
      - checkout: none

      - script: |
          uname -a
          lsb_release -a

          lscpu
          lsmem
          sudo lshw
        displayName: System

      - script: |
          df -h
          lsblk

          sudo rm -Rf /usr/local/lib/android
          sudo rm -Rf /usr/local/lib/node_modules

          df -h
          lsblk
        displayName: Disk

      - script: |
          apt list --installed
        displayName: Apps

  - job: windows
    displayName: Windows

    pool:
      vmImage: 'windows-2022'

    steps:
      - checkout: none

      - script: |
          cmd /c ver

          systeminfo
          powershell -c get-computerinfo
        displayName: System

      - powershell: |
          Get-PSDrive
        displayName: Disk

      - script: |
          choco list -i
        displayName: Apps
