directory = File.dirname(__FILE__)

load "#{directory}/../../../src/core.Vagrantfile"

bootstrap_enabled = true
server_count = 0
client_count = 0

scripts_directory = "/vagrant"

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"

  config.vm.provision "shell", privileged: false, inline: "bash #{scripts_directory}/core/initialize.sh"

  if bootstrap_enabled
    config.vm.define "bootstrap" do |config|
      config.vm.hostname = "bootstrap"

      config.vm.provision "shell", privileged: false, inline: "bash #{scripts_directory}/bootstrap/apply.sh"
    end
  end

  (1..server_count).each do |server_index|
    server_name = "server-#{server_index}"

    config.vm.define server_name do |config|
      config.vm.hostname = server_name

      config.vm.provision "shell", privileged: false, inline: "bash #{scripts_directory}/server/apply.sh"
    end
  end

  (1..client_count).each do |client_index|
    client_name = "client-#{client_index}"

    config.vm.define client_name do |config|
      config.vm.hostname = client_name

      config.vm.provision "shell", privileged: false, inline: "bash #{scripts_directory}/client/apply.sh"
    end
  end
end
